# ==============================================================================
# Job 03 : Dockerfile Hello World Debian
# ==============================================================================

# Définit l'image de base : debian en version slim (version épurée sans paquets superflus)[span_4](start_span)[span_4](end_span)
FROM debian:stable-slim

# CMD (Command) : Définit la commande exécutée par défaut au démarrage du conteneur[span_5](start_span)[span_5](end_span)
# Format Exec (recommandé en JSON array) : [exécutable, paramètre 1, paramètre 2...]
# Une fois cette commande exécutée, le processus PID 1 se termine et le conteneur s'arrête proprement[span_6](start_span)[span_6](end_span)[span_7](start_span)[span_7](end_span).
CMD ["echo", "Hello from my Debian container!"]